# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dna',
            old_name='dna',
            new_name='dna_seq',
        ),
    ]
